name: Update Profile

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/profile.yml

  schedule:
    - cron: "30 16 * * 0"

permissions:
  contents: write

jobs:
  update-profile:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=vue&show_icons=true&hide=stars&show=prs_merged&hide_rank=true
          path: media/stats.svg

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@v1.7.0
        with:
          options: user=${{ github.repository_owner }}&theme=vue
          path: media/streak.svg

      - name: Generate GitHub Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@9b38b03cac7ffb9f093a82f0ea9c634d5df62297
        with:
          username: ${{ github.repository_owner }}
          options: theme=github-light
          output_path: media/activity-graph.svg

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add media/*.svg

          if git diff --cached --quiet; then
            echo "no changes to commit"
          else
            git commit -m "chore: update github profile stats"
            git push
          fi
